# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "kampfkarren/selene@0.26.1"
stylua = "johnnymorganz/stylua@2.0.2"
rbxcloud = "Sleitnick/rbxcloud@0.13.0"
